[mgr]
show_hidden = true

[plugin]
prepend_previewers = [
  { mime = "image/tiff", run = "magick" },
]
prepend_preloaders = [
  { mime = "image/tiff", run = "magick" },
]

[opener]
pdf = [
  { run = 'open -a "Preview" "$@"', orphan = true, desc = "Preview" }
]
video = [
  { run = 'open -a "VLC" "$@"', orphan = true, desc = "VLC" }
]

[open]
rules = [
  { mime = "application/pdf", use = "pdf" },
  { mime = "video/*", use = "video" }
]
